### ISSUE TITLE
Molmim is not working in nvidia

### ISSUE THREAD

**Issue by Manvijain03** [mendsalbert/ProteinBind#1]
Access to fetch at 'https://health.api.nvidia.com/v1/biology/nvidia/molmim/generate' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Failed to load resource: health.api.nvidia.com/v1/biology/nvidia/molmim/generate:1 net::ERR_FAILED

hook.js:608 Error fetching data: TypeError: Failed to fetch
    at handleSubmit (page.tsx:68:30)
    at HTMLUnknownElement.callCallback (react-dom.development.js:20565:14)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:20614:16)
    at invokeGuardedCallback (react-dom.development.js:20689:29)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:20703:25)
    at executeDispatch (react-dom.development.js:32128:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:32160:7)
    at processDispatchQueue (react-dom.development.js:32173:5)
    at dispatchEventsForPlugins (react-dom.development.js:32184:3)
    at eval (react-dom.development.js:32374:12)
    at batchedUpdates$1 (react-dom.development.js:24953:12)
    at batchedUpdates (react-dom.development.js:28844:12)
    at dispatchEventForPluginEventSystem (react-dom.development.js:32373:3)
    at dispatchEvent (react-dom.development.js:30141:5)
    at dispatchDiscreteEvent (react-dom.development.js:30112:5)

**Comment by mendsalbert** [comment]
Try installing a CORS extension in your browser and turn it on.

**Comment by Manvijain03** [comment]
> Try installing a CORS extension in your browser and turn it on.


Failed to load resource: health.api.nvidia.com/v1/biology/nvidia/molmim/generate:1 net::ERR_FAILED

still stuck with this error so what should be done

**Comment by mendsalbert** [comment]
Kindly check the official api website for any update in url: [NVIDIA NIM ](https://build.nvidia.com/nvidia/molmim-generate?snippet_tab=Shell)

**Comment by Manvijain03** [comment]
> Kindly check the official api website for any update in url: [NVIDIA NIM ](https://build.nvidia.com/nvidia/molmim-generate?snippet_tab=Shell)

i have checked it and used the same invokeURL but it is still showing this error 
also i had generated the api key then only used it as u told in the video

**Comment by mendsalbert** [comment]
Is this the first time getting this error? Have this app worked for you on the first try?

**Comment by Manvijain03** [comment]
> Is this the first time getting this error? Have this app worked for you on the first try?

no everytime i got this error while running the app

**Comment by mendsalbert** [comment]
The api key is free to extend of calls.. so might be you have consumed all the api credit 

I do have the app running here locally with no error at all

**Comment by Manvijain03** [comment]
> The api key is free to extend of calls.. so might be you have consumed all the api credit
> 
> I do have the app running here locally with no error at all

so what should i do to resolve this error

**Comment by mendsalbert** [comment]
I recommend you read more resources online to help you solve this error 
copy the error code into google and learn more about the error and try each fixes 
https://stackoverflow.com/questions/77960822/api-call-to-authenticate-is-giving-me-failed-to-load-resource-neterr-connect
